### ISSUE TITLE
[SUGGESTION] Add String encryption

### ISSUE THREAD

**Issue by cattyngmd** [2D-Mesh-Plane/Python-Obfuscator#5]
**Please describe your suggestion in detail.**
String encryption should encrypt strings lel

**Additional context**
yes

**Comment by Madmegsox1** [comment]
yes that is on my list of things to add, just need to figure out the regex to find what's in a string lol

**Comment by Madmegsox1** [comment]
added in 38203845b218745882676d99871e5b966ae87ecb

**Comment by cattyngmd** [comment]
awesome sauce
